export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

// export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAIL = 'AUTHENTICATE_USER_FAIL';

export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

// export const CREATE_LIST = 'CREATE_LIST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAIL = 'CREATE_LIST_FAIL';
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS';
export const UPDATE_LIST_FAIL = 'UPDATE_LIST_FAIL';

export const LOAD_LISTS_SUCCESS = 'LOAD_LISTS_SUCCESS';
export const LOAD_LISTS_FAIL = 'LOAD_LISTS_FAIL';
export const INITIALIZE_LIST_EDITOR = 'INITIALIZE_LIST_EDITOR';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAIL = 'DELETE_LIST_FAIL';

export const CREATE_ITEM = 'CREATE_ITEM';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_FAIL = 'CREATE_ITEM_FAIL';

export const LOAD_ITEM_SUCCESS = 'LOAD_ITEM_SUCCESS';
export const LOAD_ITEM_FAIL = 'LOAD_ITEM_FAIL';

export const INITIATE_AJAX_CALL = 'INITIATE_AJAX_CALL';